# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose the port if needed (optional) - assuming 3000
# EXPOSE 3000

# Start the server
CMD [ "npm", "start" ]
